### ISSUE TITLE
[LightGBM] [Warning] Set TCP_NODELAY failed

### ISSUE THREAD

**Issue by rusonding** [dask/dask-lightgbm#19]
**What happened**:

>>> d_classif = dlgbm.LGBMClassifier(n_estimators=50, local_listen_port=12400)
>>> d_classif.fit(dX, dy)
Parameter tree_learner not set or set to incorrect value (None), using "data" as default
[LightGBM] [Warning] Set TCP_NODELAY failed
[LightGBM] [Info] Trying to bind port 12401...
[LightGBM] [Info] Binding port 12401 succeeded
[LightGBM] [Info] Listening...
[LightGBM] [Warning] Set TCP_NODELAY failed
[LightGBM] [Info] Trying to bind port 12400...
[LightGBM] [Info] Binding port 12400 succeeded
[LightGBM] [Warning] Set TCP_NODELAY failed
[LightGBM] [Info] Listening...
[LightGBM] [Warning] Set TCP_NODELAY failed
[LightGBM] [Warning] Set TCP_NODELAY failed
[LightGBM] [Info] Connected to rank 1
[LightGBM] [Warning] Set TCP_NODELAY failed
[LightGBM] [Info] Local rank: 0, total number of machines: 2
[LightGBM] [Info] Connected to rank 0
[LightGBM] [Info] Local rank: 1, total number of machines: 2
[LightGBM] [Warning] num_threads is set=1, n_jobs=-1 will be ignored. Current value: num_threads=1
[LightGBM] [Warning] num_threads is set=1, n_jobs=-1 will be ignored. Current value: num_threads=1

```python
import os

import dask.dataframe as dd
from dask.distributed import Client
import dask_lightgbm.core as dlgbm

client = Client() 

data = dd.read_csv('/data/platform/code/dask-lightgbm/system_tests/data/*.gz', compression='gzip', blocksize=None)

dX = data.iloc[:, :-1]
dy = data.iloc[:, -1]

d_classif = dlgbm.LGBMClassifier(n_estimators=50, local_listen_port=12400)
d_classif.fit(dX, dy)

```

**Anything else we need to know?**:

**Environment**:

- Dask version: 
dask               2.27.0
dask-glm           0.2.0
dask-lightgbm      0.1.0
dask-ml            1.7.0

- Python version: 
 3.6
- Operating System:
centos7

**Comment by SfinxCZ** [comment]
Thank you for your issue. 

Can you please clarify what exactly gone wrong? Does the code return incorrect results or is it just the warning?

**Comment by rusonding** [comment]
block!, can not return result

**Comment by FilippoCazana** [comment]
I am having a similar issue.

```python
from dask.distributed import Client
from dask_lightgbm.core import LGBMRegressor

...

with Client() as client:
    regressor = LGBMRegressor(n_estimators=50)
    regressor.fit(X_train, y_train)
```

`X_train` is a Dask DataFrame and `y_train` is a Dask Series.

The weird thing is that sometimes, calling the `.fit` method returns the correct result

```
>>> regressor.fit(X_train, y_train)

WARNING  | 2020-11-17 10:23:58,499 | dask_lightgbm.core:  Parameter tree_learner not set or set to incorrect value (None), using "data" as default
[LightGBM] [Warning] num_threads is set=2, n_jobs=-1 will be ignored. Current value: num_threads=2
LGBMRegressor(local_listen_port=12400, machines='127.0.0.1:12400',
              n_estimators=50, num_machines=1, num_threads=2, time_out=120,
              tree_learner='data')
```

Instead, other times it raises this exception:

```
>>> regressor.fit(X_train, y_train, client=client)

WARNING  | 2020-11-17 09:59:10,383 | dask_lightgbm.core:  Parameter tree_learner not set or set to incorrect value (None), using "data" as default
[LightGBM] [Warning] Set TCP_NODELAY failed
[LightGBM] [Info] Trying to bind port 12401...
[LightGBM] [Info] Binding port 12401 succeeded
[LightGBM] [Info] Listening...
[LightGBM] [Warning] Set TCP_NODELAY failed
[LightGBM] [Info] Trying to bind port 12400...
[LightGBM] [Info] Binding port 12400 succeeded
[LightGBM] [Warning] Set TCP_NODELAY failed
[LightGBM] [Info] Listening...
[LightGBM] [Warning] Set TCP_NODELAY failed
[LightGBM] [Info] [LightGBM] [Warning] Connected to rank 1Set TCP_NODELAY failed
[LightGBM] [Warning] Set TCP_NODELAY failed
[LightGBM] [Info] Connected to rank 0
[LightGBM] [Info] Local rank: 0, total number of machines: 2
[LightGBM] [Info] Local rank: 1, total number of machines: 2
[LightGBM] [Info] Finished linking network in 0.000000 seconds
distributed.worker - WARNING -  Compute Failed
Function:  _train_part
args:      ()
kwargs:    {'model_factory': <class 'lightgbm.sklearn.LGBMRegressor'>, 'params': {'boosting_type': 'gbdt', 'class_weight': None, 'colsample_bytree': 1.0, 'importance_type': 'split', 'learning_rate': 0.1, 'max_depth': -1, 'min_child_samples': 20, 'min_child_weight': 0.001, 'min_split_gain': 0.0, 'n_estimators': 50, 'n_jobs': -1, 'num_leaves': 31, 'objective': None, 'random_state': None, 'reg_alpha': 0.0, 'reg_lambda': 0.0, 'silent': True, 'subsample': 1.0, 'subsample_for_bin': 200000, 'subsample_freq': 0, 'tree_learner': 'data', 'num_threads': 2, 'machines': '127.0.0.1:12400,127.0.0.1:12401', 'local_listen_port': 12401, 'time_out': 120, 'num_machines': 2}, 'list_of_parts': [(Empty DataFrame
Columns: [ **I cannot show the columns**]
Index: [], Series([], Name: price, dtype: float64))], 'worker_addresses': ['tcp://127.0.0.1:34317', 'tcp://127
Exception: ValueError('Input data must be 2 dimensional and non empty.')
Traceback (most recent call last):
  File "/home/ubuntu/.pycharm_helpers/pydev/_pydevd_bundle/pydevd_exec2.py", line 3, in Exec
    exec(exp, global_vars, local_vars)
  File "<input>", line 1, in <module>
  File "/home/ubuntu/pycharm/my_project/venv/lib/python3.8/site-packages/dask_lightgbm/core.py", line 221, in fit
    model = train(client, X, y, params, model_factory, sample_weight, **kwargs)
  File "/home/ubuntu/pycharm/my_project/venv/lib/python3.8/site-packages/dask_lightgbm/core.py", line 131, in train
    results = client.gather(futures_classifiers)
  File "/home/ubuntu/pycharm/my_project/venv/lib/python3.8/site-packages/distributed/client.py", line 1986, in gather
    return self.sync(
  File "/home/ubuntu/pycharm/my_project/venv/lib/python3.8/site-packages/distributed/client.py", line 832, in sync
    return sync(
  File "/home/ubuntu/pycharm/my_project/venv/lib/python3.8/site-packages/distributed/utils.py", line 340, in sync
    raise exc.with_traceback(tb)
  File "/home/ubuntu/pycharm/my_project/venv/lib/python3.8/site-packages/distributed/utils.py", line 324, in f
    result[0] = yield future
  File "/home/ubuntu/pycharm/my_project/venv/lib/python3.8/site-packages/tornado/gen.py", line 762, in run
    value = future.result()
  File "/home/ubuntu/pycharm/my_project/venv/lib/python3.8/site-packages/distributed/client.py", line 1851, in _gather
    raise exception.with_traceback(traceback)
  File "/home/ubuntu/pycharm/my_project/venv/lib/python3.8/site-packages/dask_lightgbm/core.py", line 71, in _train_part
    model.fit(data, label, sample_weight=weight)
  File "/home/ubuntu/pycharm/my_project/venv/lib/python3.8/site-packages/lightgbm/sklearn.py", line 734, in fit
    super(LGBMRegressor, self).fit(X, y, sample_weight=sample_weight,
  File "/home/ubuntu/pycharm/my_project/venv/lib/python3.8/site-packages/lightgbm/sklearn.py", line 594, in fit
    self._Booster = train(params, train_set,
  File "/home/ubuntu/pycharm/my_project/venv/lib/python3.8/site-packages/lightgbm/engine.py", line 228, in train
    booster = Booster(params=params, train_set=train_set)
  File "/home/ubuntu/pycharm/my_project/venv/lib/python3.8/site-packages/lightgbm/basic.py", line 1714, in __init__
    train_set.construct().handle,
  File "/home/ubuntu/pycharm/my_project/venv/lib/python3.8/site-packages/lightgbm/basic.py", line 1081, in construct
    self._lazy_init(self.data, label=self.label,
  File "/home/ubuntu/pycharm/my_project/venv/lib/python3.8/site-packages/lightgbm/basic.py", line 827, in _lazy_init
    data, feature_name, categorical_feature, self.pandas_categorical = _data_from_pandas(data,
  File "/home/ubuntu/pycharm/my_project/venv/lib/python3.8/site-packages/lightgbm/basic.py", line 315, in _data_from_pandas
    raise ValueError('Input data must be 2 dimensional and non empty.')
ValueError: Input data must be 2 dimensional and non empty.
[LightGBM] [Warning] num_threads is set=2, n_jobs=-1 will be ignored. Current value: num_threads=2
```

**Comment by SfinxCZ** [comment]
Closing this issue, since this repo is no longer maintained and the code itself is now part of the lightgbm library (https://github.com/microsoft/LightGBM). In case that this issue is still relevant, recreate please this issue in the LightGBM repository.
